#!/bin/bash
# Uses git's autocompletion for inner commands. Assumes that git
# is installed by either Homebrew or in Linux

if hash brew 2>/dev/null; then
    completion='$(brew --prefix)/share/zsh/site-functions/_git'
else
    completion='/usr/share/git/completion/git-completion.zsh'
fi

if test -f $completion
then
    source $completion
fi
