tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'drud/ddev'
tap 'saulpw/vd'

# Essentials
brew 'bat'
brew 'chezmoi'
brew 'coreutils'
brew 'curl'
brew 'ddev'
brew 'exa'
brew 'fish'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'btop'
brew 'htmlq'
brew 'httpie'
brew 'jq'
brew 'lazygit'
brew 'neovim'
brew 'node'
brew 'ranger'
brew 'ripgrep'
brew 'visidata'
brew 'starship'
brew 'tmux'
brew 'tmuxinator'
brew 'wget'
brew 'yarn'

cask '1password'
cask '1password-cli'
cask 'akiflow'
cask 'bartender'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'fantastical'
cask 'firefox'
cask 'google-chrome'
cask 'kitty'
cask 'raycast'
cask 'spotify'
cask 'the-unarchiver'
cask 'todoist'

# Work
# cask 'bitwarden'
# cask 'figma'
# cask 'forticlient-vpn'
# cask 'microsoft-teams'
# cask 'ray'
# cask 'sizzy'
# cask 'slack'
# cask 'tableplus'
# cask 'tinkerwell'
# cask 'transmit'
# cask 'transmit'
# cask 'visual-studio-code'

# Fonts
cask 'font-blex-mono-nerd-font'
cask 'font-cascadia-code'
cask 'font-cascadia-code-pl'
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-input'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'
cask 'font-jetbrains-mono'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-victor-mono'
cask 'font-victor-mono-nerd-font'
