cask_args appdir: '/Applications'

brew 'bash'
brew 'fish'
brew 'git'
brew 'neovim/neovim/neovim'
brew 'node'
brew 'tmux'
brew 'tree'
brew 'yarn'

cask 'alfred'
cask 'dashlane'
cask 'dropbox'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'logitech-options'
cask 'postman'
cask 'sequel-pro'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vlc'
