local colorscheme = "rose-pine"

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme").init(colorscheme)
require("user.completion")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")

require("plugins/config-syntax")
require("plugins/config-explorer")
require("plugins/config-git")
require("plugins/config-navigator")
require("plugins/config-statusline")
require("plugins/config-surround")
require("plugins/config-todo")
require("plugins/config-terminal")
