local colorscheme = "rose-pine"

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme").init(colorscheme)
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.lualine")
require("user.toggleterm")
require("user.impatient")
require("user.whichkey")
require("user.navigator")
require("user.surround")
require("user.todo-comments")
