[package]
disabled = true

[php]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[directory]
style = "cyan"

[git_branch]
style = "purple"

[git_status]
style = "red"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[battery]
disabled = true
